public without sharing class PortalConstants {

    public static final String PAY_STATUS = 'Pay';
    public static final String DISPUTE_STATUS = 'Dispute';
    public static final String AWAITING_STATUS = 'Awaiting User Action';
    public static final String RENEGOCIATE_STATUS = 'Renegotiate';

    public static final String ACCEPTED_STATUS = 'Accepted';
    public static final String DECLINED_STATUS = 'Declined';


    public static final String CALLBACK_TYPE = 'CB';
    public static final String REPAIR_TYPE = 'REP';
    public static final String MAINTENANCE_TYPE = 'MNT';
    public static final String TESTING_TYPE = 'TEST';

    public static final String CATEGORY_1 = 'Category 1';
    public static final String CATEGORY_5 = 'Category 5';

    public static final String INSPECTION_PASS = 'PASS';
    public static final String INSPECTION_PASS_CONDITIONS = 'PASS W/ COND';
    public static final String INSPECTION_FAIL = 'FAIL';
    public static final String INSPECTION_INCOMPLETE = 'INCOMPLETE';

}